name: rpg_game
description: A simple text-based RPG game in Dart
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # No external dependencies required for this project

dev_dependencies:
  test: ^1.21.0
  # No dev dependencies required for this project 